import { Utensils, Shirt, Wrench, ShoppingBag, Coffee, Gift, Truck, MoreHorizontal } from "lucide-react"

export const categories = [
  {
    name: "Kuliner",
    slug: "kuliner",
    icon: Utensils,
    color: "bg-orange-100 text-orange-600",
    description: "Makanan lezat dari dapur lokal",
  },
  {
    name: "Fashion",
    slug: "fashion",
    icon: Shirt,
    color: "bg-blue-100 text-blue-600",
    description: "Pakaian dan aksesoris trendi",
  },
  {
    name: "Jasa",
    slug: "jasa",
    icon: Wrench,
    color: "bg-purple-100 text-purple-600",
    description: "Solusi profesional untuk kebutuhanmu",
  },
  {
    name: "Belanja",
    slug: "belanja",
    icon: ShoppingBag,
    color: "bg-green-100 text-green-600",
    description: "Kebutuhan sehari-hari dan lainnya",
  },
  {
    name: "Minuman",
    slug: "minuman",
    icon: Coffee,
    color: "bg-amber-100 text-amber-600",
    description: "Kopi, teh, dan minuman segar",
  },
  {
    name: "Kreatif",
    slug: "kreatif",
    icon: Gift,
    color: "bg-pink-100 text-pink-600",
    description: "Kerajinan tangan dan kado unik",
  },
  {
    name: "Logistik",
    slug: "logistik",
    icon: Truck,
    color: "bg-indigo-100 text-indigo-600",
    description: "Jasa kirim dan angkutan",
  },
  {
    name: "Lainnya",
    slug: "lainnya",
    icon: MoreHorizontal,
    color: "bg-slate-100 text-slate-600",
    description: "Kategori lainnya",
  },
]

export const shops = [
  {
    id: "1",
    name: "Dapur Bu Sinta",
    slug: "dapur-bu-sinta",
    category: "Kuliner",
    rating: 4.8,
    reviews: 124,
    location: "Tebet, Jakarta Selatan",
    image: "/indonesian-food-catering.jpg",
    verified: true,
    tags: ["Katering", "Nasi Box", "Halal"],
    description:
      "Menyediakan aneka masakan rumahan dengan cita rasa otentik. Menerima pesanan nasi box untuk berbagai acara.",
    phone: "6281234567890",
    openingHours: { start: "08:00", end: "20:00" },
    isOpen: true,
    tier: "premium",
  },
  {
    id: "2",
    name: "Kopi Senja",
    slug: "kopi-senja",
    category: "Minuman",
    rating: 4.9,
    reviews: 89,
    location: "Bandung Wetan",
    image: "/cozy-coffee-shop.png",
    verified: true,
    tags: ["Coffee", "Non-Coffee", "Snack", "Tempat Nongkrong"],
    description: "Tempat ngopi nyaman dengan biji kopi pilihan dari petani lokal Jawa Barat.",
    phone: "6281234567891",
    openingHours: { start: "10:00", end: "23:00" },
    isOpen: true,
    tier: "standard",
  },
  {
    id: "3",
    name: "Berkah Laundry",
    slug: "berkah-laundry",
    category: "Jasa",
    rating: 4.7,
    reviews: 215,
    location: "Sleman, Yogyakarta",
    image: "/laundry-service.png",
    verified: false,
    tags: ["Cuci Kiloan", "Dry Clean", "Express"],
    description: "Jasa laundry kiloan dan satuan. Bersih, wangi, dan rapi. Bisa antar jemput area Sleman.",
    phone: "6281234567892",
    openingHours: { start: "07:00", end: "21:00" },
    isOpen: false,
    tier: "standard",
  },
  {
    id: "4",
    name: "Crafty Hands",
    slug: "crafty-hands",
    category: "Kreatif",
    rating: 5.0,
    reviews: 42,
    location: "Ubud, Bali",
    image: "/handmade-crafts.png",
    verified: true,
    tags: ["Souvenir", "Handmade", "Aksesoris"],
    description: "Kerajinan tangan unik berbahan dasar alam. Cocok untuk oleh-oleh dan dekorasi rumah.",
    phone: "6281234567893",
    openingHours: { start: "09:00", end: "18:00" },
    isOpen: true,
    tier: "standard",
  },
  {
    id: "5",
    name: "Batik Kencana",
    slug: "batik-kencana",
    category: "Fashion",
    rating: 4.6,
    reviews: 56,
    location: "Solo, Jawa Tengah",
    image: "/batik-shirt.jpg",
    verified: true,
    tags: ["Batik Tulis", "Batik Cap", "Pakaian Pria"],
    description: "Pusat batik asli Solo dengan motif tradisional dan modern. Tersedia kain dan pakaian jadi.",
    phone: "6281234567894",
    openingHours: { start: "08:00", end: "17:00" },
    isOpen: true,
    tier: "standard",
  },
  {
    id: "6",
    name: "Snack Corner",
    slug: "snack-corner",
    category: "Kuliner",
    rating: 4.5,
    reviews: 30,
    location: "Malang, Jawa Timur",
    image: "/banana-chips.png",
    verified: false,
    tags: ["Cemilan", "Keripik", "Oleh-oleh"],
    description: "Pusat jajanan dan cemilan khas Malang. Renyah, gurih, dan bikin nagih.",
    phone: "6281234567895",
    openingHours: { start: "08:00", end: "20:00" },
    isOpen: true,
    tier: "standard",
  },
  {
    id: "7",
    name: "Creative Studio",
    slug: "creative-studio",
    category: "Jasa",
    rating: 4.9,
    reviews: 15,
    location: "Online (Jakarta)",
    image: "/generic-logo-design.png",
    verified: true,
    tags: ["Desain Grafis", "Logo", "Social Media"],
    description: "Jasa desain grafis profesional untuk branding UMKM. Cepat, revisi mudah, dan harga bersahabat.",
    phone: "6281234567896",
    openingHours: { start: "09:00", end: "17:00" },
    isOpen: true,
    tier: "standard",
  },
  {
    id: "8",
    name: "Leather Craft",
    slug: "leather-craft",
    category: "Fashion",
    rating: 4.8,
    reviews: 78,
    location: "Garut, Jawa Barat",
    image: "/leather-shoes.png",
    verified: true,
    tags: ["Sepatu Kulit", "Dompet", "Tas"],
    description: "Produk kulit asli Garut kualitas ekspor. Awet, elegan, dan bergaransi.",
    phone: "6281234567897",
    openingHours: { start: "08:00", end: "17:00" },
    isOpen: true,
    tier: "standard",
  },
]

export const products = [
  {
    id: "101",
    name: "Paket Nasi Liwet Komplit",
    shopId: "1",
    price: 35000,
    image: "/indonesian-food-catering.jpg",
    description: "Nasi liwet dengan ayam goreng, tahu, tempe, ikan asin, dan sambal lalap.",
    category: "Kuliner",
  },
  {
    id: "102",
    name: "Sambal Bawang Bu Rudy",
    shopId: "1",
    price: 25000,
    image: "/sambal-jar.jpg",
    description: "Sambal bawang pedas nampol, cocok untuk teman makan nasi hangat.",
    category: "Kuliner",
  },
  {
    id: "201",
    name: "Es Kopi Susu Gula Aren",
    shopId: "2",
    price: 18000,
    image: "/cozy-coffee-shop.png",
    description: "Perpaduan espresso house blend dengan susu segar dan gula aren asli.",
    category: "Minuman",
  },
  {
    id: "202",
    name: "V60 Manual Brew",
    shopId: "2",
    price: 25000,
    image: "/steaming-coffee-cup.png",
    description: "Seduhan kopi manual dengan biji pilihan (Arabica Gayo/Toraja/Bali).",
    category: "Minuman",
  },
  {
    id: "301",
    name: "Cuci Komplit (Cuci + Setrika)",
    shopId: "3",
    price: 6000,
    unit: "kg",
    image: "/laundry-service.png",
    description: "Layanan cuci bersih, kering, dan setrika rapi. Harga per kilogram.",
    category: "Jasa",
  },
  {
    id: "401",
    name: "Tas Anyaman Rotan",
    shopId: "4",
    price: 150000,
    image: "/handmade-crafts.png",
    description: "Tas selempang wanita dari anyaman rotan asli, stylish dan etnik.",
    category: "Kreatif",
  },
  {
    id: "501",
    name: "Kemeja Batik Pria Modern",
    shopId: "5",
    price: 150000,
    image: "/batik-shirt.jpg",
    description: "Kemeja batik print katun prima, adem dan tidak luntur. Tersedia size M-XL.",
    category: "Fashion",
  },
  {
    id: "601",
    name: "Keripik Pisang Coklat",
    shopId: "6",
    price: 15000,
    image: "/banana-chips.png",
    description: "Keripik pisang kepok dengan balutan bubuk coklat tebal.",
    category: "Kuliner",
  },
  {
    id: "701",
    name: "Jasa Desain Logo UMKM",
    shopId: "7",
    price: 250000,
    image: "/generic-logo-design.png",
    description: "Paket desain logo termasuk file master (AI/EPS), PNG transparan, dan 3x revisi.",
    category: "Jasa",
  },
  {
    id: "801",
    name: "Sepatu Pantofel Pria",
    shopId: "8",
    price: 450000,
    image: "/leather-shoes.png",
    description: "Sepatu kerja pria bahan kulit sapi asli, sol karet anti slip.",
    category: "Fashion",
  },
]

export const users = [
  {
    id: "u1",
    name: "Super Admin",
    email: "admin@jadikios.com",
    role: "superadmin",
  },
  {
    id: "u2",
    name: "Siti Aminah",
    email: "siti@dapurbusinta.com",
    role: "mitra",
    shopId: "1",
  },
  {
    id: "u3",
    name: "Budi Santoso",
    email: "budi@gmail.com",
    role: "customer",
  },
  {
    id: "u4",
    name: "Joko Widodo",
    email: "joko@gmail.com",
    role: "customer",
  },
]

export const payments = [
  {
    id: "p1",
    shopId: "1",
    shopName: "Dapur Bu Sinta",
    amount: 99000,
    status: "paid",
    date: "2023-10-01",
    type: "subscription",
    plan: "Premium Bulanan",
  },
  {
    id: "p2",
    shopId: "2",
    shopName: "Kopi Senja",
    amount: 99000,
    status: "pending",
    date: "2023-10-05",
    type: "subscription",
    plan: "Premium Bulanan",
  },
]

export const reviews = [
  {
    id: "r1",
    productId: "101",
    shopId: "1",
    userId: "u3",
    userName: "Budi Santoso",
    rating: 5,
    comment: "Rasanya otentik banget! Mengingatkan masakan ibu di kampung.",
    date: "2023-10-15",
  },
  {
    id: "r2",
    productId: "101",
    shopId: "1",
    userId: "u4",
    userName: "Siti Aminah",
    rating: 4,
    comment: "Enak, tapi sambalnya terlalu pedas buat saya.",
    date: "2023-10-16",
  },
  {
    id: "r3",
    productId: "201",
    shopId: "2",
    userId: "u3",
    userName: "Budi Santoso",
    rating: 5,
    comment: "Kopinya mantap, gula arennya kerasa asli.",
    date: "2023-10-18",
  },
]

export const platformReviews = [
  {
    id: "pr1",
    userId: "u2",
    userName: "Siti Aminah",
    role: "Mitra",
    rating: 5,
    comment: "Sangat terbantu dengan aplikasi ini. Omzet naik 30% sejak gabung!",
    date: "2023-09-01",
  },
  {
    id: "pr2",
    userId: "u3",
    userName: "Budi Santoso",
    role: "Customer",
    rating: 4,
    comment: "Aplikasi mudah digunakan, tapi tolong tambah fitur tracking kurir.",
    date: "2023-09-10",
  },
]

export const orders = [
  {
    id: "ORD-001",
    userId: "u3",
    shopId: "1",
    customer: "Ahmad Fauzi",
    items: [
      { name: "Nasi Goreng Spesial", quantity: 2, price: 25000 },
      { name: "Es Teh Manis", quantity: 2, price: 5000 },
    ],
    total: 60000,
    status: "pending", // pending, processing, ready, delivering, completed, cancelled
    paymentMethod: "qris", // qris, cash
    paymentStatus: "paid", // paid, unpaid
    type: "delivery", // delivery, pickup
    date: "2024-01-20 14:30",
    phone: "0812-3456-7890",
    address: "Jl. Merdeka No. 10, Jakarta Selatan",
  },
  {
    id: "ORD-002",
    userId: "u4",
    shopId: "2",
    customer: "Siti Nurhaliza",
    items: [
      { name: "Kopi Latte", quantity: 1, price: 25000 },
      { name: "Croissant", quantity: 2, price: 15000 },
    ],
    total: 55000,
    status: "processing",
    paymentMethod: "qris",
    paymentStatus: "paid",
    type: "pickup",
    date: "2024-01-20 13:15",
    phone: "0813-4567-8901",
    address: "-",
  },
]
